### ISSUE TITLE
Is an APK release to download via GitHub planned? Or F-Droid or Izzy, whichever is easier?

### ISSUE THREAD

**Issue by natzki** [soupslurpr/BeauTyXT#110]
Just wondering, or if it's something of less priority atm. I really like Accrescent but atm BeauTyXT is the only app I would need from downloading the entire "app store".

Greetz and Thank you

**Comment by soupslurpr** [comment]
Hi, at this time an APK release on GitHub isn't planned. The only app store / method of getting BeauTyXT that I think fits my requirements is Accrescent. Its really nice and fairly easy to use. Thanks and have a good day/night!

**Comment by soupslurpr** [comment]
You can get an apk in the Assets part of the release on GitHub if you really need it for some uses. It is recommended to install BeauTyXT through the Accrescent app store at https://accrescent.app/ for more security and automatic updates.
