### ISSUE TITLE
[Feature request] - Give users option to change ic_launcher styles/color.

### ISSUE THREAD

**Issue by akc3n** [soupslurpr/BeauTyXT#115]
@soupslurpr thank you for making this beautiful materialyou designed markdown editor. I love it. 

I'd like to add a feature request for UI enhancement and for people like me, a better UX experience. As you may well know, there are apps that give users the option to change the launcher icon based on a select few styles build in with an app.

To me, having a dark grey material theme is perfect, however, the [launcher icon is so bright and colorful](https://github.com/soupslurpr/BeauTyXT/blob/master/app/src/main/ic_launcher-accrescent.png), that I feel optically overwhelmed at times.

If you have a moment to spare and indulge the idea, the [ReadYou materialyou rss reader app has a this color scheme for their launcher icon](https://github.com/Ashinch/ReadYou/blob/main/app/src/main/ic_launcher-playstore.png) to match the rest of colors of the app. It's very easy on the eyes to people like me and others perhaps too..?

Purpose:  to consider having an optional feature for users to select an alternative app launcher icon. Sample:

![ic_launcher-accrescent~2](https://github.com/soupslurpr/BeauTyXT/assets/71854332/ff47eef3-4e42-4541-87b4-efe80c74db07)

Thank you for your time reading this. And great job on the app.

Edit: I know that users have the option of settings the toggle on for themed icons in the wallpapers and styles of their android system settings too....

**Comment by soupslurpr** [comment]
Thanks, I don't have any problem with having such an option as long as it isn't difficult to implement.

**Comment by soupslurpr** [comment]
I feel like it might be better if instead of a gray theme, it could be modified to use slightly less vibrant colors if that's the issue?

**Comment by soupslurpr** [comment]
I couldn't find a good way to change the icon.

**Comment by akc3n** [comment]
> I feel like it might be better if instead of a gray theme, it could be modified to use slightly less vibrant colors if that's the issue?

Hmm, I'm not sure tbh. I love the gray theme and I'm only referring to https://github.com/soupslurpr/BeauTyXT/blob/master/app/src/main/ic_launcher-accrescent.png specifically.

**Comment by soupslurpr** [comment]
You mean the one shown in Accrescent?

**Comment by akc3n** [comment]
> I couldn't find a good way to change the icon.

Thank you for looking into this. And no worries. It's no big deal. I love your app!
