### ISSUE TITLE
make it possible to edit the file name by clicking the file name

### ISSUE THREAD

**Issue by life00** [soupslurpr/BeauTyXT#116]
When the file is opened in the preview/editing mode there is a file name displayed above. I feel like it is extremely intuitive to make it clickable and editable directly from the app.

**Comment by soupslurpr** [comment]
The "file name" shown is actually not guaranteed to be the file's actual name. It usually is, but it might not be. Its called "display name". Its a bit unclear what this means exactly, anyways there is a method to change the display name of the document. I think its a little complicated to make it editable from just tapping on the label, but it should be possible to do from an alert dialog, similar to delete file, share, share as, export, etc. A "Rename" option I suppose.
