### ISSUE TITLE
Optionally remember and display last edited file for quick access

### ISSUE THREAD

**Issue by matchboxbananasynergy** [soupslurpr/BeauTyXT#12]
There could be an option which shows you the last edited file in case you want to continue editing that.

https://developer.android.com/training/data-storage/shared/documents-files#:~:text=optionally%20specify%20the%20URI%20of%20the%20file%20that%20the%20file%20picker%20should%20display%20when%20it%20first%20loads

**Comment by soupslurpr** [comment]
I decided I don't really want this. I think selecting the recent tab in the system file explorer is easy enough. I also don't want to save things like the file name or path in the app.
