### ISSUE TITLE
Typst doesn't show math

### ISSUE THREAD

**Issue by vvsagar** [soupslurpr/BeauTyXT#123]
Hello,

When I try to write add something like `$alpha$` in a typst document I get the error `current font does not support math`.
Am I doing something wrong? Is there a way to fix it?

**Comment by soupslurpr** [comment]
Hi, make sure to set the math font to Stix Two Math, which supports math.

`#show math.equation: set text(font: "Stix Two Math")`

You can also set text to Stix Two Text for consistency.

`#set text(font: "Stix Two Text")`

**Comment by vvsagar** [comment]
That works, thank you :)
