### ISSUE TITLE
The app keeps crashing

### ISSUE THREAD

**Issue by shuen2023** [soupslurpr/BeauTyXT#138]
Hello! I've downloaded the latest version, 0.21. However, when I try to create or open .typ files and long press on my phone's keyboard to input, the app crashes. My device is running the Huawei HarmonyOS. I didn't encounter this issue with the previous 0.20 version. It only happens with this latest version, 0.21. Could you please look into this? Thank you!

**Comment by shuen2023** [comment]
[logcat.txt](https://github.com/soupslurpr/BeauTyXT/files/14734379/logcat.txt)

**Comment by soupslurpr** [comment]
Hi! Does this happen with Markdown as well? From a quick look at the logs it seems to be something related to the new security feature of running each file with its own isolated process Rust library. Maybe your device doesn't support it?

**Comment by shuen2023** [comment]
> 你好！Markdown 和纯文本也会发生这种情况吗？快速查看日志似乎可能与使用自己的独立进程 Rust 库运行每个文件的新安全功能有关。也许您的设备不支持？

Yes, markdown is like this too。 So.  Can I only use version 0.2?

**Comment by soupslurpr** [comment]
Unfortunately yes, but can you tell me what device you have?

**Comment by shuen2023** [comment]
> Unfortunately yes, but can you tell me what device you have?

Huawei’s Hongmeng OS looks like Android 12 on ADB https://github.com/Awesome-HarmonyOS/HarmonyOS/tree/master

**Comment by soupslurpr** [comment]
You might not be running Android it seems. Sorry, only Android is supported.

**Comment by shuen2023** [comment]
> 看来您可能没有运行 Android。抱歉，仅支持 Android。

OK, thanks。

**Comment by NarwhalPrince** [comment]
Getting app crash on GrapheneOS when entering text in a Markdown file.
[BeauTyXT log b807d6835c31.txt](https://github.com/soupslurpr/BeauTyXT/files/14766011/BeauTyXT.log.b807d6835c31.txt)

**Comment by soupslurpr** [comment]
Does it only crash on a specific file? If you make a new file does it still crash? If it crashes when typing something specific, please let me know.

**Comment by soupslurpr** [comment]
I just reproduced it. I'm not sure how this went past my testing.

**Comment by NarwhalPrince** [comment]
Just did a little more testing, it crashes in the markdown editor when the renderer is enabled.

**Comment by NarwhalPrince** [comment]
Let me know if you need a different log

**Comment by soupslurpr** [comment]
seems the issue is that some dependency needs new sys calls after updating it, I should have tested it. I apologize. A new release will be out very soon to fix this.

**Comment by soupslurpr** [comment]
Note that the issue this is for seems to be unrelated as Typst works fine and I did test that

**Comment by soupslurpr** [comment]
I just released 0.21.1, @NarwhalPrince it works fine now.

@shuen2023 While I don't think it will fix your issue as it seems unrelated, it won't hurt to try.

**Comment by shuen2023** [comment]
> I just released 0.21.1, @NarwhalPrince it works fine now.
> 
> @shuen2023 While I don't think it will fix your issue as it seems unrelated, it won't hurt to try.

Unfortunately it still shuts down unexpectedly.  I may need to change my phone.  Thanks

**Comment by soupslurpr** [comment]
@shuen2023 can you try the newest version? This issue wasn't completely resolved in the previous one.

**Comment by shuen2023** [comment]
> @shuen2023 can you try the newest version? This issue wasn't completely resolved in the previous one.

Yes.  Now it works fine.  I rarely come across such an easy-to-use APP, thank you for everything.

**Comment by soupslurpr** [comment]
That's good, thanks :)
