### ISSUE TITLE
update minskd version to 27

### ISSUE THREAD

**Issue by litttley** [soupslurpr/BeauTyXT#157]
the minskd  version is too higher for some platforms

**Comment by soupslurpr** [comment]
Unfortunately, a minimum SDK of 29 is needed as BeauTyXT uses getApplication<Application>().bindIsolatedService(). SDK 27 is Android 8.1, which is very outdated. The latest version of Android is 14. Android 8.1 does not get security updates any more. I'd advise you to get a new device.
