### ISSUE TITLE
Set app as default for .md files

### ISSUE THREAD

**Issue by gasparzuker** [soupslurpr/BeauTyXT#158]
Hi, I just found this app today and I believe it's a great app, thank you
I tried to ser this app as default open apñ for .md files but the app doesn't appear between the options
I don't know if this is a bug or if the feature is not implemented yet. I would also like to know of there's a way to set it manually

**Comment by soupslurpr** [comment]
Could you send me a screenshot of the menu it doesn't appear in? It does support setting it as the default app for opening .md files.

**Comment by gasparzuker** [comment]
The files app opens the .md file automatically with the app, but when I try to open a file from whatsapp it doesn't works
![Screenshot_20240627_104741_Android System](https://github.com/soupslurpr/BeauTyXT/assets/64669290/a6186527-f413-4c47-b106-53ea11921183)

**Comment by soupslurpr** [comment]
Its likely a WhatsApp issue. You can try installing this app https://github.com/MuntashirAkon/AppManager/releases/download/v3.1.6/AppManager_v3.1.6.apk and opening the file with it and sending a screenshot of the result to see what WhatsApp is putting in the intent.

**Comment by gasparzuker** [comment]
URI	intent://com.whatsapp.provider.media/item/89b4e0a9-e8d4-4ecf-841c-51ae0c63aafc#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000001;end

VERSION	1
ACTION	android.intent.action.VIEW
DATA	content://com.whatsapp.provider.media/item/89b4e0a9-e8d4-4ecf-841c-51ae0c63aafc
TYPE	application/octet-stream
FLAGS	0x3000001

MATCHING ACTIVITIES	12
0	LABEL  	Billetera de Google
  	NAME   	com.google.android.gms.pay.deeplink.AliasSavePkPassActivity
  	PACKAGE	com.google.android.gms
1	LABEL  	AnkiDroid
  	NAME   	com.ichi2.anki.IntentHandler
  	PACKAGE	com.ichi2.anki
2	LABEL  	Reddit
  	NAME   	com.reddit.vault.feature.cloudbackup.restore.RedditVaultFileActivity
  	PACKAGE	com.reddit.frontpage
3	LABEL  	Rutas
  	NAME   	com.samsung.android.app.shealth.tracker.sport.route.view.TrackerSportRouteCardListActivity
  	PACKAGE	com.sec.android.app.shealth
4	LABEL  	Escáner
  	NAME   	io.github.muntashirakon.AppManager.scanner.ScannerActivity
  	PACKAGE	io.github.muntashirakon.AppManager
5	LABEL  	Explorar
  	NAME   	io.github.muntashirakon.AppManager.apk.explorer.AppExplorerActivity
  	PACKAGE	io.github.muntashirakon.AppManager
6	LABEL  	Información de la aplicación
  	NAME   	io.github.muntashirakon.AppManager.details.AppInfoActivity
  	PACKAGE	io.github.muntashirakon.AppManager
7	LABEL  	Visor de manifiestos
  	NAME   	io.github.muntashirakon.AppManager.details.manifest.ManifestViewerActivity
  	PACKAGE	io.github.muntashirakon.AppManager
8	LABEL  	Instalar
  	NAME   	io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity
  	PACKAGE	io.github.muntashirakon.AppManager
9	LABEL  	Interceptador
  	NAME   	io.github.muntashirakon.AppManager.intercept.ActivityInterceptor
  	PACKAGE	io.github.muntashirakon.AppManager
10	LABEL  	Keepass2Android
  	NAME   	crc64dd09b2a2e58bb27d.SelectCurrentDbActivity
  	PACKAGE	keepass2android.keepass2android
11	LABEL  	Daylio
  	NAME   	net.daylio.activities.BackupAdvancedActivity
  	PACKAGE	net.daylio

**Comment by soupslurpr** [comment]
As you can see, WhatsApp is setting the type as `application/octet-stream` in the intent. The correct type for Markdown is `text/markdown`.

**Comment by soupslurpr** [comment]
`application/octet-stream` is the MIME type for arbitrary binary data.

"Generic binary data (or binary data whose true type is unknown) is application/octet-stream."
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

**Comment by gasparzuker** [comment]
Thank you!
