### ISSUE TITLE
Colors & PDFs

### ISSUE THREAD

**Issue by VulcanElf** [soupslurpr/BeauTyXT#44]
Is there a way to implement, either on the user-side, or dev-side, to incorporate colors?

Allowing to be saved as a PDF, doc, etc would be helpful.

Thanks!

**Comment by soupslurpr** [comment]
What does incorporate colors mean? Being able to specify colors for specific text?

**Comment by soupslurpr** [comment]
You can specify colors in markdown. Markdown editing and rendering support was added in v0.6.0.

**Comment by soupslurpr** [comment]
You can make an issue for exporting to PDF's if you want.
