### ISSUE TITLE
Beautify app icon

### ISSUE THREAD

**Issue by julianfairfax** [soupslurpr/BeauTyXT#50]
I tried this app and I like it. It does exactly I need it to do.

However, the icon really needs some design work. The current one is really not that nice looking in my opinion.

I think it would be good if it were just blue and white. Like the themed icon.

I can look into this myself, but I'm not an Android developer.

**Comment by soupslurpr** [comment]
Hello, this is really just a matter of personal preference. If you like the themed icon, then use it. But I don't think the default icon should be the themed icon. In my opinion it is pretty fine how it is right now, but of course improvements could possibly be made, such as having the rounded corner be even.

**Comment by soupslurpr** [comment]
The app icon was recently updated in https://github.com/soupslurpr/BeauTyXT/commit/a6a5b99167c99f3b199a723b00032ffe035dd03b
