### ISSUE TITLE
share button

### ISSUE THREAD

**Issue by Reflux0301** [soupslurpr/BeauTyXT#9]
![image](https://github.com/soupslurpr/BeauTyXT/assets/130855216/6b80db5b-71c2-4bf8-a2d8-a955243fe381)

**Comment by soupslurpr** [comment]
After some further thought, you can either just select all while having the file open or share the file from your file manager instead. This is far simpler and will keep the app simple.

**Comment by harish-kumaran** [comment]
Just my suggestion that even Secure PDF viewer has a share button. Some(most of the)times people just view a file and then immediately share it. I think as an end user this is something essential and almost every app has this. Anyways it's finally your app your rules👍

**Comment by soupslurpr** [comment]
A pull request adding this to the 3 button menu would be accepted now.

**Comment by soupslurpr** [comment]
It would have to share it as a file, not the text of it.

**Comment by soupslurpr** [comment]
A share button was added in the export dropdown menu in #111. It shares the content of the file as text, and not an actual file. This is because it seems its more complicated than I thought it was to share an actual file.
